import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Sparkles } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { getAIReviewHistory } from "../services/aiService.js";
import { getErrorMessage } from "../utils/getErrorMessage.js";
import DifficultyBadge from "../components/problems/DifficultyBadge.jsx";

const ReviewHistoryPage = () => {
  const [reviews, setReviews] = useState([]);
  const [selectedReview, setSelectedReview] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");

  const fetchReviews = async () => {
    try {
      setIsLoading(true);
      setError("");
      const response = await getAIReviewHistory();
      setReviews(response.data || []);
    } catch (err) {
      setError(getErrorMessage(err) || "Failed to fetch review history");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchReviews();
  }, []);

  return (
    <article className="problems-page-container">
      <header className="problems-hero problems-hero-purple">
        <div className="hero-content">
          <p className="eyebrow">AI Review Assistant</p>
          <h1>Your AI Code Reviews</h1>
          <p className="hero-subtext">
            A complete history of code reviews generated by Google Gemini AI.
            Analyze complexity, bugs, edge cases, and best practices.
          </p>
        </div>
      </header>

      {isLoading ? (
        <div className="page-status" style={{ padding: "4rem 0" }}>
          <div className="spinner" style={{ margin: "0 auto 1.5rem" }} />
          <p>Loading your AI review history...</p>
        </div>
      ) : error ? (
        <div className="alert error">{error}</div>
      ) : reviews.length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-icon">
            <Sparkles size={24} />
          </div>
          <h3>No Reviews Yet</h3>
          <p>
            When you solve problems in the workspace, click the &quot;AI
            Review&quot; button to get smart feedback.
          </p>
          <Link
            to="/problems"
            className="primary-button"
            style={{ display: "inline-flex", marginTop: "1.5rem" }}
          >
            Explore Problems
          </Link>
        </div>
      ) : (
        <div className="table-responsive">
          <table className="problems-table">
            <thead>
              <tr>
                <th>Problem</th>
                <th>Difficulty</th>
                <th>Language</th>
                <th>Reviewed At</th>
                <th style={{ textAlign: "right" }}>Report</th>
              </tr>
            </thead>
            <tbody>
              {reviews.map((rev) => (
                <tr key={rev._id}>
                  <td>
                    <Link
                      to={`/problems/${rev.problemId?._id || rev.problemId}`}
                      className="problem-link-title"
                    >
                      {rev.problemId?.title || "Deleted Problem"}
                    </Link>
                  </td>
                  <td>
                    {rev.problemId?.difficulty ? (
                      <DifficultyBadge difficulty={rev.problemId.difficulty} />
                    ) : (
                      <span className="verdict-badge">—</span>
                    )}
                  </td>
                  <td style={{ fontWeight: 600 }}>
                    {rev.language.toUpperCase()}
                  </td>
                  <td className="muted-text">
                    {new Date(rev.createdAt).toLocaleString()}
                  </td>
                  <td style={{ textAlign: "right" }}>
                    <button
                      className="solve-action-btn"
                      onClick={() => setSelectedReview(rev)}
                      type="button"
                    >
                      View Report
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {selectedReview && (
        <div className="submission-detail-overlay">
          <div
            className="submission-detail-modal"
            style={{ maxWidth: "800px", width: "90%" }}
          >
            <header className="modal-header">
              <div>
                <h3>
                  AI Review:{" "}
                  {selectedReview.problemId?.title || "Deleted Problem"}
                </h3>
                <span className="history-date">
                  Generated on{" "}
                  {new Date(selectedReview.createdAt).toLocaleString()}
                </span>
              </div>
              <button
                className="close-button"
                onClick={() => setSelectedReview(null)}
                type="button"
              >
                &times;
              </button>
            </header>

            <div className="modal-body">
              <div className="modal-meta-grid">
                <div>
                  <span>Language</span>
                  <strong>{selectedReview.language.toUpperCase()}</strong>
                </div>
                <div>
                  <span>Problem Link</span>
                  {selectedReview.problemId?._id ? (
                    <Link
                      to={`/problems/${selectedReview.problemId._id}`}
                      className="modal-link"
                    >
                      Go to Workspace
                    </Link>
                  ) : (
                    <strong className="muted-text">Unavailable</strong>
                  )}
                </div>
              </div>

              <div className="modal-code-section">
                <h4>Submitted Code</h4>
                <pre className="modal-code-display">
                  <code>{selectedReview.code}</code>
                </pre>
              </div>

              <div className="ai-review-section">
                <div className="ai-title-group" style={{ marginBottom: "1rem" }}>
                  <Sparkles className="ai-sparkle-icon" size={20} />
                  <h3 style={{ margin: 0 }}>AI Feedback & Recommendations</h3>
                </div>
                <div className="ai-review-markdown">
                  <ReactMarkdown>{selectedReview.review}</ReactMarkdown>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </article>
  );
};

export default ReviewHistoryPage;
